//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDemo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSample1Soap")]
    public interface ServiceSample1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceDemo.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceDemo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceDemo.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeepInSession", ReplyAction="*")]
        WebServiceDemo.ServiceReference1.KeepInSessionResponse KeepInSession(WebServiceDemo.ServiceReference1.KeepInSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeepInSession", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.KeepInSessionResponse> KeepInSessionAsync(WebServiceDemo.ServiceReference1.KeepInSessionRequest request);
        
        // CODEGEN: Generating message contract since element name GetListFromSessionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListFromSession", ReplyAction="*")]
        WebServiceDemo.ServiceReference1.GetListFromSessionResponse GetListFromSession(WebServiceDemo.ServiceReference1.GetListFromSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListFromSession", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.GetListFromSessionResponse> GetListFromSessionAsync(WebServiceDemo.ServiceReference1.GetListFromSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceDemo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceDemo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepInSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepInSession", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.KeepInSessionRequestBody Body;
        
        public KeepInSessionRequest() {
        }
        
        public KeepInSessionRequest(WebServiceDemo.ServiceReference1.KeepInSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeepInSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public KeepInSessionRequestBody() {
        }
        
        public KeepInSessionRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepInSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepInSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.KeepInSessionResponseBody Body;
        
        public KeepInSessionResponse() {
        }
        
        public KeepInSessionResponse(WebServiceDemo.ServiceReference1.KeepInSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KeepInSessionResponseBody {
        
        public KeepInSessionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListFromSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListFromSession", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.GetListFromSessionRequestBody Body;
        
        public GetListFromSessionRequest() {
        }
        
        public GetListFromSessionRequest(WebServiceDemo.ServiceReference1.GetListFromSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListFromSessionRequestBody {
        
        public GetListFromSessionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListFromSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListFromSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.ServiceReference1.GetListFromSessionResponseBody Body;
        
        public GetListFromSessionResponse() {
        }
        
        public GetListFromSessionResponse(WebServiceDemo.ServiceReference1.GetListFromSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListFromSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceDemo.ServiceReference1.ArrayOfString GetListFromSessionResult;
        
        public GetListFromSessionResponseBody() {
        }
        
        public GetListFromSessionResponseBody(WebServiceDemo.ServiceReference1.ArrayOfString GetListFromSessionResult) {
            this.GetListFromSessionResult = GetListFromSessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSample1SoapChannel : WebServiceDemo.ServiceReference1.ServiceSample1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSample1SoapClient : System.ServiceModel.ClientBase<WebServiceDemo.ServiceReference1.ServiceSample1Soap>, WebServiceDemo.ServiceReference1.ServiceSample1Soap {
        
        public ServiceSample1SoapClient() {
        }
        
        public ServiceSample1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSample1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSample1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSample1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDemo.ServiceReference1.HelloWorldResponse WebServiceDemo.ServiceReference1.ServiceSample1Soap.HelloWorld(WebServiceDemo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name) {
            WebServiceDemo.ServiceReference1.HelloWorldRequest inValue = new WebServiceDemo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            WebServiceDemo.ServiceReference1.HelloWorldResponse retVal = ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.HelloWorldResponse> WebServiceDemo.ServiceReference1.ServiceSample1Soap.HelloWorldAsync(WebServiceDemo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string name) {
            WebServiceDemo.ServiceReference1.HelloWorldRequest inValue = new WebServiceDemo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            return ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDemo.ServiceReference1.KeepInSessionResponse WebServiceDemo.ServiceReference1.ServiceSample1Soap.KeepInSession(WebServiceDemo.ServiceReference1.KeepInSessionRequest request) {
            return base.Channel.KeepInSession(request);
        }
        
        public void KeepInSession(string name) {
            WebServiceDemo.ServiceReference1.KeepInSessionRequest inValue = new WebServiceDemo.ServiceReference1.KeepInSessionRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.KeepInSessionRequestBody();
            inValue.Body.name = name;
            WebServiceDemo.ServiceReference1.KeepInSessionResponse retVal = ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).KeepInSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.KeepInSessionResponse> WebServiceDemo.ServiceReference1.ServiceSample1Soap.KeepInSessionAsync(WebServiceDemo.ServiceReference1.KeepInSessionRequest request) {
            return base.Channel.KeepInSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.KeepInSessionResponse> KeepInSessionAsync(string name) {
            WebServiceDemo.ServiceReference1.KeepInSessionRequest inValue = new WebServiceDemo.ServiceReference1.KeepInSessionRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.KeepInSessionRequestBody();
            inValue.Body.name = name;
            return ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).KeepInSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDemo.ServiceReference1.GetListFromSessionResponse WebServiceDemo.ServiceReference1.ServiceSample1Soap.GetListFromSession(WebServiceDemo.ServiceReference1.GetListFromSessionRequest request) {
            return base.Channel.GetListFromSession(request);
        }
        
        public WebServiceDemo.ServiceReference1.ArrayOfString GetListFromSession() {
            WebServiceDemo.ServiceReference1.GetListFromSessionRequest inValue = new WebServiceDemo.ServiceReference1.GetListFromSessionRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.GetListFromSessionRequestBody();
            WebServiceDemo.ServiceReference1.GetListFromSessionResponse retVal = ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).GetListFromSession(inValue);
            return retVal.Body.GetListFromSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.GetListFromSessionResponse> WebServiceDemo.ServiceReference1.ServiceSample1Soap.GetListFromSessionAsync(WebServiceDemo.ServiceReference1.GetListFromSessionRequest request) {
            return base.Channel.GetListFromSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDemo.ServiceReference1.GetListFromSessionResponse> GetListFromSessionAsync() {
            WebServiceDemo.ServiceReference1.GetListFromSessionRequest inValue = new WebServiceDemo.ServiceReference1.GetListFromSessionRequest();
            inValue.Body = new WebServiceDemo.ServiceReference1.GetListFromSessionRequestBody();
            return ((WebServiceDemo.ServiceReference1.ServiceSample1Soap)(this)).GetListFromSessionAsync(inValue);
        }
    }
}
